server:
  port: 8090

spring:
  application:
    name: crm-poc-domain-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.crm.poc: DEBUG
    io.camunda: INFO
